import type { Metadata } from "next";

import "./globals.css";
import NavigasiWrapper from "./components/NavigasiWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="mx-auto border sm:w-[390px] w-full min-h-screen">
          <NavigasiWrapper />
          {children}
        </div>
      </body>
    </html>
  );
}
